<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FuyangPC" name="au.com.transurban.retailweb.regression.tests.NewTest" tests="1" failures="1" timestamp="7 May 2015 07:16:31 GMT" time="0.001" errors="0">
  <testcase name="f" time="0.001" classname="au.com.transurban.retailweb.regression.tests.NewTest">
    <failure type="java.lang.RuntimeException" message="Could not start Selenium session: null">
      <![CDATA[java.lang.RuntimeException: Could not start Selenium session: null
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:109)
	at au.com.transurban.retailweb.regression.tests.NewTest.beforeMethod(NewTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.NullPointerException
	at java.net.URLEncoder.encode(Unknown Source)
	at org.openqa.selenium.net.Urls.urlEncode(Urls.java:62)
	at com.thoughtworks.selenium.DefaultRemoteCommand.getCommandURLString(DefaultRemoteCommand.java:59)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:98)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:272)
	at com.thoughtworks.selenium.HttpCommandProcessor.start(HttpCommandProcessor.java:234)
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:100)
	... 27 more
]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- au.com.transurban.retailweb.regression.tests.NewTest -->
